/* A trilha apresenta o estado; as transições são validadas em core.js. */
(function(root) {
  'use strict';
  root.renderGame = function(C, game) {
    const level = C.levels[game.level], completed = game.level;
    const trail = `<aside class="trail-panel" aria-label="Trilha das vinte fases"><div class="trail-heading"><span class="eyebrow">Seu caminho</span><strong>${completed}<small> / 20 fases</small></strong></div><progress max="20" value="${completed}" aria-label="Fases concluídas"></progress>${['Começar','Construir','Praticar','Conquistar'].map((name,group)=>`<div class="trail-group"><h3><span>0${group+1}</span> ${name}</h3><ol start="${group*5+1}" class="trail-nodes">${C.levels.slice(group*5,group*5+5).map((l,offset)=>{const i=group*5+offset,status=i<completed?'Concluída':i===completed?'Fase atual':'Bloqueada';return `<li><span class="trail-node ${i<completed?'done':i===completed?'current':'locked'}" ${i===completed?'aria-current="step"':''} aria-label="Fase ${i+1}: ${l.title}. ${status}." title="${l.title} · ${status}">${i<completed?'<span aria-hidden="true">✓</span>':i+1}</span></li>`;}).join('')}</ol></div>`).join('')}<div class="trail-legend"><span><i class="legend-done"></i> Concluída</span><span><i class="legend-current"></i> Atual</span><span><i class="legend-locked"></i> Bloqueada</span></div><p class="trail-note">Cinco acertos abrem a próxima fase. Seu progresso é salvo automaticamente.</p></aside>`;
    const intro = `<div class="game-intro"><div><div class="eyebrow">Jogo de escolhas</div><h1>Sua trilha de conquistas</h1><p class="lead">20 fases. 100 perguntas. Uma nova descoberta a cada escolha.</p></div><span class="game-counter">${completed * 5}<small> / 100 superadas</small></span></div>`;
    let card;
    if (!level) {
      card = `<section class="card game-card finale"><div class="victory-mark" aria-hidden="true">★</div><span class="eyebrow">Jornada completa</span><h2>Você chegou ao topo!</h2><p class="completion-number">20 <span>de 20 fases</span></p><p>Você superou as 100 perguntas e conquistou o título de <strong>Guardião do Cofre</strong>.</p><div class="earned-badges"><span>✓ Escolhas conscientes</span><span>✓ Metas planejadas</span><span>✓ Orçamento organizado</span></div><p class="muted">Agora leve suas descobertas para as conversas e os planos da sua família.</p><a class="button" href="#metas">Cuidar das minhas metas →</a></section>`;
    } else {
      const count = game.answers.length, score = C.score(game);
      const top = `<div class="phase-heading"><span class="phase-tag">Fase ${game.level+1} / 20</span><span class="muted">${level.description}</span></div><h2 class="phase-title">${level.title}</h2><div class="question-steps" aria-label="${count} de 5 perguntas respondidas">${level.questions.map((q,i)=>`<span class="question-step ${i<count?(game.answers[i]===q.best?'right':'wrong'):i===count?'active':''}">${i<count?(game.answers[i]===q.best?'✓':'×'):i+1}<span class="sr-only">${i<count?(game.answers[i]===q.best?' Correta':' Incorreta'):' Não respondida'}</span></span>`).join('')}</div>`;
      if (game.pending) {
        const q = level.questions[count-1], correct = game.answers[count-1]===q.best;
        card = `<section class="card game-card" id="play-area">${top}<div class="answer-feedback ${correct?'is-right':'is-learning'}"><span class="feedback-symbol" aria-hidden="true">${correct?'✓':'↺'}</span><div><h3>${correct?'Boa escolha!':'Mais uma chance de aprender'}</h3><p>${correct?'Você acertou esta pergunta.':'Esta resposta não está correta. Veja o porquê.'}</p></div></div><p class="question-recap">${q.story}</p><p class="chosen-answer"><strong>Sua resposta:</strong> ${q.options[game.answers[count-1]]}</p>${!correct?`<p class="correct-answer"><strong>Resposta correta:</strong> ${q.options[q.best]}</p>`:''}<p class="lesson">${q.lesson}</p><button class="game-next" data-action="next">${count===5?'Ver resultado da fase':'Próxima pergunta'} →</button></section>`;
      } else if (count===5) {
        const passed = score===5;
        card = `<section class="card game-card" id="play-area">${top}<div class="phase-result"><span class="badge ${passed?'':'retry-badge'}">${passed?'Fase superada':'Continue tentando'}</span><h3>${passed?'Cinco acertos. Mais uma conquista!':'Você está no caminho.'}</h3><div class="result">${score} <span>/ 5</span></div><p>${passed?(game.level===19?'Todas as perguntas desta jornada foram superadas.':'Uma nova fase com cinco perguntas diferentes espera por você.'):'Para avançar, acerte as cinco perguntas na mesma tentativa. Revise o que faltou e tente esta fase novamente.'}</p></div>${!passed?`<div class="review-list"><h3>Vale revisar</h3>${level.questions.filter((q,i)=>game.answers[i]!==q.best).map(q=>`<details><summary>${q.story}</summary><p><strong>${q.options[q.best]}</strong></p><p>${q.lesson}</p></details>`).join('')}</div>`:''}<button class="game-next" data-action="${passed?'advance':'retry'}">${passed?(game.level===19?'Concluir jornada':'Desbloquear próxima fase'):'Tentar esta fase novamente'} →</button></section>`;
      } else {
        const q=level.questions[count];
        card=`<section class="card game-card" id="play-area">${top}<div class="question-meta"><span>Pergunta ${count+1} de 5</span><span>Valores fictícios</span></div><h3 class="story" id="question-text">${q.story}</h3><div class="answer-options" role="group" aria-labelledby="question-text">${q.options.map((o,i)=>`<button class="option" data-action="answer" data-value="${i}"><span class="option-letter" aria-hidden="true">${String.fromCharCode(65+i)}</span><span>${o}</span></button>`).join('')}</div><p class="game-hint">Leia com calma. Cada resposta vem com uma explicação.</p></section>`;
      }
    }
    return `${intro}<div class="game-layout">${card}${trail}</div>`;
  };
})(window);
